/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface ApiKeys {
  base_url: string;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  id: Generated<string>;
  name: string;
  secret_ciphertext: string;
  secret_updated_at: Generated<Timestamp>;
  type: string;
  updated_at: Generated<Timestamp>;
}

export interface AuditEvents {
  action: string;
  actor_user_id: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  metadata: Generated<Json>;
  summary: string;
  target_id: string;
  target_type: string;
}

export interface Bookings {
  calendar_event_id: string | null;
  cancel_source: string | null;
  cancelled_at: Timestamp | null;
  cancelled_by_user_id: string | null;
  created_at: Generated<Timestamp>;
  ends_at: Timestamp;
  id: Generated<string>;
  starts_at: Timestamp;
  status: string;
  testbed_id: string;
  testbed_type_id: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
  version: Generated<number>;
}

export interface HolAuthAccount {
  accessToken: string | null;
  accessTokenExpiresAt: Timestamp | null;
  accountId: string;
  createdAt: Generated<Timestamp>;
  id: string;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: Timestamp | null;
  scope: string | null;
  updatedAt: Timestamp;
  userId: string;
}

export interface HolAuthSession {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  ipAddress: string | null;
  token: string;
  updatedAt: Timestamp;
  userAgent: string | null;
  userId: string;
}

export interface HolAuthUser {
  createdAt: Generated<Timestamp>;
  email: string;
  emailVerified: boolean;
  id: string;
  image: string | null;
  name: string;
  updatedAt: Generated<Timestamp>;
}

export interface HolAuthVerification {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  identifier: string;
  updatedAt: Generated<Timestamp>;
  value: string;
}

export interface Jobs {
  attempts: Generated<number>;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  idempotency_key: string;
  kind: string;
  last_error: string | null;
  locked_until: Timestamp | null;
  payload: Json;
  run_at: Generated<Timestamp>;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface RateLimits {
  bucket_key: string;
  count: number;
  created_at: Generated<Timestamp>;
  window_start: Timestamp;
}

export interface TestbedClients {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  kind: string;
  name: string;
  position: number;
  testbed_id: string;
  url: string;
}

export interface Testbeds {
  authentik_group_pk: string | null;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  id: Generated<string>;
  idp_api_key_id: string | null;
  lms_url: string;
  name: string;
  portal_url: string;
  slug: string;
  testbed_type_id: string;
  updated_at: Generated<Timestamp>;
}

export interface TestbedTypes {
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  duration_unit: string;
  duration_value: number;
  id: Generated<string>;
  name: string;
  updated_at: Generated<Timestamp>;
}

export interface Users {
  auth_user_id: string | null;
  authentik_pending_saga: Generated<boolean>;
  authentik_user_pk: number | null;
  company: string | null;
  created_at: Generated<Timestamp>;
  deactivated_at: Timestamp | null;
  email: string;
  email_verified_at: Timestamp | null;
  id: Generated<string>;
  name: string;
  role: string;
  set_password_pending: Generated<boolean>;
  status: Generated<string>;
  timezone: string;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  api_keys: ApiKeys;
  audit_events: AuditEvents;
  bookings: Bookings;
  "hol_auth.account": HolAuthAccount;
  "hol_auth.session": HolAuthSession;
  "hol_auth.user": HolAuthUser;
  "hol_auth.verification": HolAuthVerification;
  jobs: Jobs;
  rate_limits: RateLimits;
  testbed_clients: TestbedClients;
  testbed_types: TestbedTypes;
  testbeds: Testbeds;
  users: Users;
}
