// Generated by kysely-codegen from the live schemas (hol_app, hol_auth).
// Empty until feature 3 (data model) adds the first tables.
// eslint-disable-next-line @typescript-eslint/no-empty-object-type
export interface DB {}
